alias it='cd /Users/leiwang/Learning/projects/it/'
alias startps='pg_ctl -D /usr/local/var/postgres/data -l /tmp/postgre_server.log start'
alias stopps='pg_ctl -D /usr/local/var/postgres/data stop -s -m fast'
alias yyproxy="ssh -N -f -D 1080 root@106.186.117.131"
alias pxy="ssh -qTfnN -D 1090 root@198.74.48.54"
alias blog='cd /Users/leiwang/Learning/wldandan.github.com' 
alias dir="ls -R | grep ":" | sed -e 's/://' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'"
alias mou='open -a Mou'
alias ls='ls -FG'
alias ll='ls -lFG'
alias la='ls -AFG'
alias l='ls -hlFG'

alias dotfiles='cd /Users/leiwang/Work/dotfiles/'
alias rm='rm -i' # DON'T USE rm -rf ALWAYS, BE CAREFUL
alias rdf='rm -rf'

alias gd='cd ~/Downloads'

alias hi=' history | less +G'

alias vimrc='vim ~/.vimrc'

alias grep='grep -a --color=auto'

alias psa='ps aux'

alias k9='kill -9'

alias bi='bundle install'
alias bu='bundle update'
alias bl='bundle list'
alias be='bundle exec'
alias cuke='be cucumber '
alias cucumber='cuke'
alias brails='be rails'

alias sll='svn log | less'
alias spec='be spec --format documentation --color --profile'

alias g='git'
alias d='git diff'

alias git-manual-page='open http://schacon.github.com/git/git.html'

alias resource='source ~/.bashrc'

alias wtf='tail -f /var/log/{dmesg,messages,*{,/*}{log,err}}'

#alias gradle='gradle -q'
alias itpub='cd /Users/leiwang/Downloads/Learning/Books/download_itpub' 
alias ted='cd /Users/leiwang/Downloads/Learning/Git/script/ruby/download_ted'
alias dens='cd /Users/leiwang/Project/rails/awsdens'
alias hi='cd /Users/leiwang/Work/rea/casa/home-ideas'
alias jwtest='cd /Users/leiwang/Work/rea/casa/casa-jetwire-test-script'
alias casa-api='cd /Users/leiwang/Work/rea/syndication/casa-api'
alias rapi='API_DOMAIN=casa RAILS_ENV=development rails s'
alias listingxml='cd /web/app/jetwire/dataloader-data/casa/incoming/jetwire-xml'
alias jwdev='cd /Users/leiwang/Work/rea/jetwire-casa/jetwire-casa-master/'
alias hackday='cd /Users/leiwang/Work/rea/hackday/'
alias rea='cd ~/Work/rea'
alias vm='cd ~/Work/vm'
alias webserver='cd /Library/WebServer/Documents'
alias goagent='cd /Users/leiwang/Apps/goagent/local && python proxy.py'
alias redis='redis-server /usr/local/etc/redis.conf'
alias loaddata='/opt/rea/apps/lmds/feeder/bin/dataloader.sh -t listing -c rea'
alias solr-stg='ssh -A -i ~/.aws/guojifang-stg-ap-northeast-1.pem -L 8983:solr:8983 ec2-user@54.238.198.167 -N'

alias e2e='cd /Users/leiwang/Work/rea/casa/end-2-end'
alias china='cd /Users/leiwang/Work/rea/china'
alias resi='cd /Users/leiwang/Work/rea/resi'
alias linode='ssh -qTfnN -D 7070 root@176.58.114.68'
alias rea='cd /Users/leiwang/Work/rea'
alias feccc='cd /Users/leiwang/Learning/projects/feccc/jd'
alias spikes='cd ~/Learning/spikes'
alias biz='cd /Users/leiwang/Work/rea/biz'
alias jdkhome='cd /Library/Java/JavaVirtualMachines'


alias setjdk16='export JAVA_HOME=$(/usr/libexec/java_home -v 1.6)'
alias setjdk17='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)'
alias setjdk18='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)'

