# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="eastwood"
ZSH_THEME="powerline"
POWERLINE_HIDE_HOST_NAME=true
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
 DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
 DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git rvm gem)
plugins=(git node brew bundle cap gem github osx rails ruby rvm svn textmate)
source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=$PATH::/Users/leiwang/.rvm/bin:/usr/local/heroku/bin:/Users/leiwang/.gvm/vertx/current/bin:/Users/leiwang/.gvm/springboot/current/bin:/Users/leiwang/.gvm/lazybones/current/bin:/Users/leiwang/.gvm/groovyserv/current/bin:/Users/leiwang/.gvm/groovy/current/bin:/Users/leiwang/.gvm/griffon/current/bin:/Users/leiwang/.gvm/grails/current/bin:/Users/leiwang/.gvm/gradle/current/bin:/Users/leiwang/.gvm/gaiden/current/bin:/Users/leiwang/myhome/:/Users/leiwang/Work/feeder-casa/bin:/Users/leiwang/Work/apps/apache-cxf-2.6.0/bin:/usr/local/sbin:/usr/local/bin:/Users/leiwang/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/leiwang/Work/apps/apache-tomcat-6.0.35/bin:/Users/leiwang/Framework/scala-2.10.2/bin:/usr/local/Cellar/postgresql/9.2.4/bin:/Users/leiwang/Learning/dotfiles/ext/:/Users/leiwang/Work/bin:/Users/leiwang/Work/dotfiles/bin

source ~/.bash_profile
#source ~/.bash_aliases

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
PATH=$PATH:$HOME/.rvm/bin

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

source "$HOME/.gvm/bin/gvm-init.sh"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
